version: '3.5'

# https://hub.docker.com/r/tchiotludo/kafkahq
# https://github.com/tchiotludo/kafkahq

services:
    kafkahq:
        container_name: kafkahq
        environment:
            KAFKAHQ_CONFIGURATION: |
                kafkahq:
                    connections:
                        docker-kafka-server:
                            properties:
                                bootstrap.servers: "10.1.3.6:9092,10.1.3.10:9092"
        hostname: kafkahq
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/kafkahq:${KAFKAHQ_VERSION:-0.11.0}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m" 
        networks:
            - kafkahq-net
        ports:
            - 8080:8080
        volumes:
            - ./app/application.yml:/app/application.yml

networks:
     kafkahq-net:
             name: kafkahq-container-net 
